repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        additional_dependencies:
          - 'pydantic'
        exclude: '(?x)(test\_.*|conftest\.py|docs/conf\.py)'
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        files: ^(src)\/.*
        additional_dependencies:
          - 'pydocstyle[toml]'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.283
    hooks:
      - id: ruff
